### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by arnair** [crystalui/lightbox#2]
Hello, i just bought the Lightbox gesture enabled, and  i don't know how to install it i m used to npm install and when i try to intall it manually i don't know where to put things import things ets.. Could you make me a step by step guide to install it for angular nobs?(i am using angular 7 and ionic 4)  thanks

**Comment by drozhzhin-n-e** [comment]
@arnair Hello. Copy the `lightbox` folder from the archive that you downloaded from gumroad.com and place it in the `/src/app/` folder of your application. Then, import the module as shown here: https://github.com/crystalui/lightbox/blob/master/src/app/app.module.ts

`import { CrystalLightboxModule } from './lightbox/lightbox.module';`

```
  imports: [
    CrystalLightboxModule
  ],
```

**Comment by arnair** [comment]
I added this code to my component and i got this error:

```
<div lightbox-group>
    <img src="https://www.w3schools.com/howto/img_forest.jpg" lightbox [fullImage]="{path: 'https://www.w3schools.com/howto/img_forest.jpg' }" />
</div>
```

![image](https://user-images.githubusercontent.com/12446891/51551812-8e5a5a80-1e6f-11e9-9ddc-99a2a2af28e5.png)


This is my setup:
![image](https://user-images.githubusercontent.com/12446891/51552035-0b85cf80-1e70-11e9-8044-9c661f65986a.png)

**Comment by drozhzhin-n-e** [comment]
You import the `CrystalLightboxModule` into an `app.module` and then use the lightbox in another module: `chat.module`. You need to import `CrystalLightboxModule` into each module in which you use the lightbox. And also download the lightbox version 1.0.1 from https://gumroad.com/l/EQWEl and update your application.

**Comment by arnair** [comment]
cool now it looks it's working correctly, the only thing i have is that i don't know how to do the binding in the [fullImage] i tried this but don't work (the src works)
`  <img src="{{message.imgUrl}}" lightbox [fullImage]="{path: '{{message.imgUrl}}' }" />  `

**Comment by drozhzhin-n-e** [comment]
try `<img src="{{message.imgUrl}}" lightbox [fullImage]="{path: message.imgUrl}" />`

**Comment by arnair** [comment]
Now is working perfect :)

thanks
